### ISSUE TITLE
Error "Cannot read property 'children' of undefined"

### ISSUE THREAD

**Issue by jpvincent** [paulirish/devtools-timeline-model#16]
Hi

I encoutered a JS error when analysing this file : [TimelineRawData-20161030T091130.json.zip](https://github.com/paulirish/devtools-timeline-model/files/560348/TimelineRawData-20161030T091130.json.zip)
recorded with Chrome 54 on mac OSX 64 bit, with only JS profile activated and 2X CPU slowdown. It was run using Node 6.3.0

The error : 

```
chrome-devtools-frontend/front_end/sdk/CPUProfileDataModel.js:61
            return node.children.reduce((acc, node) => acc + computeHitCountForSubtree(node), node.hitCount);
                       ^
TypeError: Cannot read property 'children' of undefined
    at computeHitCountForSubtree (chrome-devtools-frontend/front_end/sdk/CPUProfileDataModel.js:61:24)
    at Object.WebInspector.CPUProfileDataModel._translateProfileTree (chrome-devtools-frontend/front_end/sdk/CPUProfileDataModel.js:71:30)
    at Object.WebInspector.CPUProfileDataModel (chrome-devtools-frontend/front_end/sdk/CPUProfileDataModel.js:38:29)
    at Object.WebInspector.TimelineModel._processThreadEvents (chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js:737:42)
    at Object.WebInspector.TimelineModel.setEvents (chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js:504:22)
    at SandboxedModel.init (evalmachine.<anonymous>:74:25)
    at new ModelAPI (/Users/jpv/Insync/Société/Clients/lexpress.fr/stat-cpu-domain/node_modules/devtools-timeline-model/index.js:29:18)
    at Object.<anonymous> (/Users/jpv/Insync/Société/Clients/lexpress.fr/stat-cpu-domain/cpu-abuser.js:28:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

Thanks

**Comment by hrgui** [comment]
Got the same issue as well - with different environment variables: Node 7.0.0, JS Profile activated only.

**Comment by paulirish** [comment]
Thanks. master branch should resolve this problem. Need to get it shipped.

**Comment by jpvincent** [comment]
Hi, fine
The version number is still 1.1.6 on NPM, shall we wait a bit more ?

**Comment by jpvincent** [comment]
The master branch definitely resolves the problem, thanks for that !
However nothing has been published on npm, I had to switch my package.json dependancies from 1.1.6 to a direct inclusion of the git master branch … I'm not very confortable with that, we would appreciate you to publish a new version on npm :)

**Comment by paulirish** [comment]
Will do!

**Comment by paulirish** [comment]
version 1.2.2 is out. :)

**Comment by jpvincent** [comment]
great, thanks !
