### ISSUE TITLE
RangeError: Maximum call stack size exceeded due to console.assert patching

### ISSUE THREAD

**Issue by hrgui** [paulirish/devtools-timeline-model#23]
**Error:**

RangeError: Maximum call stack size exceeded
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:33:26)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)
        at Console.console.assert [as __originalAssert] (chrome-devtools-frontend/front_end/platform/utilities.js:36:11)

**Sample script**
````javascript
let model = new DevtoolsTimelineModel(page._tracingEntries);
let timelineModel = model.timelineModel();
````

**Where did the data come from?**
Chrome RDP

**Params passed in to Chrome RDP**
````json
{
"TRACE_OPTIONS": "sampling-frequency=10000",
"TRACE_CATEGORIES": ["-*", "devtools.timeline", "disabled-by-default-devtools.timeline", "disabled-by-default-devtools.timeline.frame", "toplevel", "blink.console", "disabled-by-default-devtools.timeline.stack", "disabled-by-default-devtools.screenshot", "disabled-by-default-v8.cpu_profile"]
}
````

**Comment by hrgui** [comment]
I'm going to try if this change https://github.com/ChromeDevTools/devtools-frontend/commit/e5855e5b0eca72b49bd62f1688c3dffa5534f446 fixes the problem.

**Comment by paulirish** [comment]
@hrgui nice debugging. I ran into troubles with the console code and have since updated this module to include the latest devtools source which has https://github.com/ChromeDevTools/devtools-frontend/commit/e5855e5b0eca72b49bd62f1688c3dffa5534f446

you can try the new 1.3.0, but i imagine you'll still get "Multiple sessions in trace". 
Can you confirm that?  also see #15

**Comment by hrgui** [comment]
@paulirish so the reason why I had multiple sessions in trace is because i had duplicate copies of events, which triggered that assert.

I will try the new 1.3.0 to ensure that the max call stack trace is not appearing anymore.

**Comment by paulirish** [comment]
k sounds good!
