### ISSUE TITLE
Event WaitSyncToken has already been started

### ISSUE THREAD

**Issue by dhirajbodicherla** [paulirish/devtools-timeline-model#28]
**Problem:**
Loading events using `var model = new DevtoolsTimelineModel(events)` throws an error.

**Scenario:**
I'm running tests using webdriverio. Along with the tests I'm trying to gather perf information using Tracing from [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface).

At the end of webdriverio's test spec, chrome-remote-interface is able to gather Trace information into a json file. Uploading this json file to chrome://tracing gives out meaningful information. However, when I try to parse the json file with devtools-timeline-model I get the below error (added a trace in the source code)

> Trace: Event WaitSyncToken has already been started 
> at SDK.TracingModel._addAsyncEvent (chrome-devtools-frontend/front_end/sdk/TracingModel.js:397:17)
> at SDK.TracingModel._processPendingAsyncEvents (chrome-devtools-frontend/front_end/sdk/TracingModel.js:326:14)
> at SDK.TracingModel.tracingComplete (chrome-devtools-frontend/front_end/sdk/TracingModel.js:138:10)
> at SDK.TracingModel.setEventsForTest (chrome-devtools-frontend/front_end/sdk/TracingModel.js:126:10)
> at SandboxedModel.init (evalmachine.<anonymous>:125:24)
> at new ModelAPI (/Users/dbodicherla/Developer/devtoolparser/node_modules/devtools-timeline-model/index.js:29:18)
> at Object.<anonymous> (/Users/dbodicherla/Developer/devtoolparser/index.js:6:13)
> at Module._compile (module.js:573:30)
> at Object.Module._extensions..js (module.js:584:10)
> at Module.load (module.js:507:32)

**Env**
webdriverio: 4.8.6
Chrome version: 63.0.3239.132 (Official Build) (64-bit)

**Comment by paulirish** [comment]
Interesting! Haven't run into this error before.  You're collecting the trace with cri, right? So you're attached to a specific tab?

I ask because I'd expect DTM to have problems with a trace collected by webdriver, but the cri way should be fine..

**Comment by dhirajbodicherla** [comment]
Yes, I am using the trace from CRI and yes, to a specific tab. 
After many many hours I finally figured out that chrome wasn't running with `--disable-gpu`. After passing the flag DTM is running without errors.

This issue can be closed. But do you think the README.md should mention about the flag?
