### ISSUE TITLE
Cannot read property error of undefined. while using Tracealyser library which using devtools time line as dependency.

### ISSUE THREAD

**Issue by ssivanatarajan** [paulirish/devtools-timeline-model#34]

**Comment by ssivanatarajan** [comment]
Any update on this issue?

**Comment by ssivanatarajan** [comment]
@paulirish

**Comment by raviregina** [comment]
1. goto this file location **node_modules/chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js line.no:267.**
2. Simply comment that line and run  your code.

**Comment by goelayu** [comment]
Sometimes this error is observed if your timeline trace has some missing samples. 
Try loading the trace using the graphic timeline viewer and see if the console gives you any error.

**Comment by raviregina** [comment]
@paulirish I got this same error while parsing the timeline profile.

Here is the log trace,

TypeError: Cannot read property 'error' of undefined
    at TimelineModel.TimelineModel._extractCpuProfile (chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js:471:22)
    at TimelineModel.TimelineModel._injectJSFrameEvents (chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js:482:31)
    at TimelineModel.TimelineModel._processThreadEvents (chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js:505:23)
    at TimelineModel.TimelineModel.setEvents (chrome-devtools-frontend/front_end/timeline_model/TimelineModel.js:197:16)
    at SandboxedModel.init (evalmachine.<anonymous>:133:25)
    at new ModelAPI (/Users/ravi-6704/Documents/test/anonFunctionnew-copy/node_modules/devtools-timeline-model/index.js:29:18)
    at initial (/Users/ravi-6704/Documents/test/anonFunctionnew-copy/index.js:18:17)
    at Object.<anonymous> (/Users/ravi-6704/Documents/test/anonFunctionnew-copy/index.js:38:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)


It would be very helpful if you provide the solution.




Thanks in advance!!!

**Comment by lreher** [comment]
Hey I know I'm 3 years late to the party, but if anyone is struggling with this issue take a look at the code for:
https://www.npmjs.com/package/tracealyzer

The issue is some events need to be cleaned up before parsing.
