### ISSUE TITLE
ENOENT errors when calling DevtoolsTimelineModel

### ISSUE THREAD

**Issue by jfsiii** [paulirish/devtools-timeline-model#7]
When I call `new DevtoolsTimelineModel` I get the following error:

```
‣ node -e "var DevtoolsTimelineModel = require('devtools-timeline-model'); new DevtoolsTimelineModel;"
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/jschulz/Sites/automated-chrome-profiling/node_modules/devtools-timeline-model/node_modules/chrome-devtools-frontend/front_end/common/Object.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at requireval (evalmachine.<anonymous>:10:20)
    at evalmachine.<anonymous>:26:1
    at new ModelAPI (/Users/jschulz/Sites/automated-chrome-profiling/node_modules/devtools-timeline-model/index.js:15:25)
    at [eval]:1:65
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:413:34)
```

I'm using `node -e` here, but I get the same thing in the REPL and in tools which use this project, like [`speedline`](https://github.com/pmdartus/speedline).

I believe the issue is that the `requireval` function assumes `npm@2` style paths and I'm using `nmp@3`. `chrome-devtools-frontend/front_end/common/Object.js` does exist, but as a peer of `devtools-timeline-model` not in a child `node_modules` directory.

```
‣ ls -alh node_modules/ | grep devtools
drwxr-xr-x   12 jschulz  staff   408B Apr 10 13:11 chrome-devtools-frontend
drwxr-xr-x   12 jschulz  staff   408B Apr 10 13:11 devtools-timeline-model
‣ls -alh node_modules/chrome-devtools-frontend/front_end/common/Object.js
-rw-r--r--  1 jschulz  staff   6.2K Feb  2 18:10 node_modules/chrome-devtools-frontend/front_end/common/Object.js
‣ node -v
v5.10.0
 ‣ npm -v
3.8.3
```

**Comment by paulirish** [comment]
@jfsiii Ah yeah. I think your conclusion is right on point here. 

Curious how speedline gets things working and doesn't hit the same bug..   cc @pmdartus (Crazy cool project, btw!)

**Comment by paulirish** [comment]
Yup I get the same error when trying out speedline: 

![image](https://cloud.githubusercontent.com/assets/39191/14414148/ef266ea2-ff5b-11e5-8d3f-21d21fb9cc2d.png)

--------------------------------


Fix about to land...

**Comment by paulirish** [comment]
pushing to github apparently isn't well supported by jetblue's wifi, so I can't do it right now.. but here's the patch I'm trying to push. Should fix all this.


```diff
commit d1919e67b997d83a298b9f62e3850245988a709d
Author: Paul Irish <paul.irish@gmail.com>
Date:   Sun Apr 10 20:47:36 2016 -0400

    resolve correct module location. fixes #7

diff --git a/lib/timeline-model.js b/lib/timeline-model.js
index c38717b..fdc3ef1 100644
--- a/lib/timeline-model.js
+++ b/lib/timeline-model.js
@@ -1,15 +1,19 @@
 'use strict'
 
-var fs = require('fs');
+const fs = require('fs');
+const path = require('path');
+const resolve = require('resolve');
 
 // In order to maintain consistent global scope across the files,
 // and share natives like Array, etc, We will eval things within
 // our sandbox
 function requireval(path){
-  var filesrc = fs.readFileSync(__dirname + '/node_modules/' + path, 'utf8');
+  var res = resolve.sync(path, { basedir: __dirname })
+  var filesrc = fs.readFileSync(res, 'utf8');
   eval(filesrc + '\n\n//# sourceURL=' + path);
 }
 
+
 // establish our sandboxed globals
 this.window = this.self = this.global = this
 this.console = console
@@ -19,7 +23,7 @@ this.Runtime = this.TimelineModelTreeView = this.TreeElement = {}
 this.WorkerRuntime = this.Protocol = {}
 
 // polyfills
-requireval('../lib/api-stubs.js')
+requireval('./lib/api-stubs.js')
 
 // chrome devtools frontend
 requireval('chrome-devtools-frontend/front_end/common/Object.js')
@@ -41,9 +45,9 @@ requireval('chrome-devtools-frontend/front_end/timeline/TimelineIRModel.js')
 requireval('chrome-devtools-frontend/front_end/timeline/TimelineFrameModel.js')
 
 // minor configurations
-requireval('../lib/devtools-monkeypatches.js')
+requireval('./lib/devtools-monkeypatches.js')
 // polyfill the bottom-up and topdown tree sorting
-requireval('../lib/timeline-model-treeview.js')
+requireval('./lib/timeline-model-treeview.js')
 
 class SandboxedModel {
 
diff --git a/package.json b/package.json
index be4be0a..d50cb82 100644
--- a/package.json
+++ b/package.json
@@ -26,7 +26,8 @@
     "timeline"
   ],
   "dependencies": {
-    "chrome-devtools-frontend": "1.0.382117"
+    "chrome-devtools-frontend": "1.0.382117",
+    "resolve": "1.1.7"
   },
   "devDependencies": {
     "ava": "^0.12.0",
```

I'll push and bump when i'm back online tonight.

**Comment by paulirish** [comment]
v1.0.18 with this fix is published.

**Comment by pmdartus** [comment]
@jfsiii @paulirish Thanks for surfacing the bug. I was running into the same issue on Travis only. Now I understand why 😄
